#:schema node_modules/wrangler/config-schema.json
name = "sublink-workers"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d86abe5f94d244f4bd67bfb54731fa71" }
]

[assets]
directory = "./public"
